### ISSUE TITLE
Docker instance. 500 - Server Error Whoops, something went wrong on our servers. 

### ISSUE THREAD

**Issue by malyyigor34** [MarceauKa/shaark#106]
Docker compose file
```

version: '2.2'
services:
  shaark:
    image: shaark
    build: https://github.com/MarceauKa/shaark.git#master
    container_name: shaark
    restart: unless-stopped
#    volumes:
#      - "./env:/app/.env"
    ports:
      - "8120:80/tcp"
    networks:
      - shaark
      - nginx_net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  mariadb:
    image: mariadb
    container_name: mariadb_shaark
    restart: unless-stopped
    volumes:
      - /data/shaark/opt/shaark/mariadb:/var/lib/mysql
    networks:
      - shaark
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword9867ow3q459087w980
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_DATABASE: homestead
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis
    container_name: redis_shaark
    restart: unless-stopped
    volumes:
      - /data/shaark/opt/shaark/redis:/data
    networks:
      - shaark
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  shaark:
    name: shaark_net
  nginx_net:
    name: nginx_net

```
