### ISSUE TITLE
Feedback welcome on custom Docker image

### ISSUE THREAD

**Issue by frenchvandal** [MarceauKa/shaark#70]
I decided to create this spin-off not to pollute #69 

Despite all the tips provided on the former issue, I have not managed to install Shaark with MariaDB so for now I stick to SQLite.

Here is my Dockerfile:

```
FROM alpine/git as builder
WORKDIR /tmp
RUN set -x \
    && git clone https://github.com/MarceauKa/shaark.git shaark

FROM php:7-alpine
WORKDIR /app
COPY --from=builder /tmp/shaark /app
RUN set -x && \
        touch database/shaark.sqlite && \
        mv .env.example .env && \
        \
        sed -i s/APP_ENV=local/APP_ENV=production/ .env && \
        sed -i s/APP_DEBUG=true/APP_DEBUG=false/ .env && \
        sed -i 's|APP_URL=http:\/\/dev.shaark|APP_URL=https:\/\/normco.re|' .env && \
        sed -i s/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/ .env && \
        sed -i 's|DB_DATABASE=homestead|DB_DATABASE=\/app\/database\/shaark\.sqlite|' .env && \
        #test with Redis
        sed -i s/REDIS_HOST=127.0.0.1/REDIS_HOST=redis/ .env && \
        sed -i s/CACHE_DRIVER=file/CACHE_DRIVER=redis/ .env && \
        sed -i s/QUEUE_CONNECTION=sync/QUEUE_CONNECTION=redis/ .env && \
        sed -i s/SESSION_DRIVER=file/SESSION_DRIVER=redis/ .env && \
        sed -i s/REDIS_HOST=127.0.0.1/REDIS_HOST=redis/ .env && \
        #test with Redis
        \
        apk -U upgrade && \
        apk add --no-cache --update openssl \
        zip \
        unzip \
        oniguruma-dev \
        zlib-dev libpng-dev \
        libzip-dev \
        postgresql-dev \
        gmp \
        gmp-dev \
        nodejs \
        npm && \
        echo "**** install Python ****" && \
        apk add --no-cache python3 && \
        if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
        \
        curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/bin/youtube-dl && \
        chmod a+rx /usr/bin/youtube-dl && \
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
        docker-php-ext-install pdo mbstring gd exif zip sockets pdo_mysql pgsql pdo_pgsql gmp bcmath && \
        apk --no-cache add pcre-dev ${PHPIZE_DEPS} && \
        pecl install -o -f redis && \
        docker-php-ext-enable redis && \
        apk del pcre-dev ${PHPIZE_DEPS} && \
        rm -rf /tmp/* && \
        \
        composer install --no-dev -o && \
        npm install -g @nesk/puphpeteer --no-save --unsafe-perm=true --allow-root && \
        php artisan optimize && \
        php artisan view:clear && \
        \
        php artisan key:generate && \
        php artisan storage:link && \
        php artisan config:cache && \
        php artisan migrate --seed -n --force

VOLUME /app

CMD php artisan serve --host=0.0.0.0 --port=80
EXPOSE 80
```

My `docker-compose.yml` file:
```yml
version: "3.7"

volumes:
  app:
  data:

services:
  shaark:
    #image: frenchvandal/shaark:attack
    image: shaark:attack
    build: .
    container_name: shaark
    restart: always
    depends_on:
      - redis
    volumes:
      - app:/app:rw
      - data:/data:rw

  redis:
    image: redis:alpine3.11
    container_name: redis
    restart: unless-stopped
    volumes:
      - data:/data:rw

networks:
  default:
    external:
      name: firefly
```
(firefly is the default network of all my containers)

A few comments about things I added but not sure really sure if they are actually needed:
- I included the git clone directly in the Dockerfile
- I added the PHP extension for Redis,
- For archiving with Redis, I added Python 3, youtube-dl with curl, npm/nodejs for puphpeteer

The image builds successfully and Shaark is up when I hit the URL.

Globally it is functional, except a few things:
- Shaark does not display correctly if I do not put the actual URL in the APP_URL entry in .env
- if I enable the comments in the settings, clicking on any permalink leads to 500 error
- pictures sometimes fail to load when I drop a picture in the new album form
- search only display results if SQL is enabled
- hitting save when adding a new album generates a `server error` message, though when I go back to the front page, the new album is actually published
- archiving seems not to work, using the Test buttons gets a `server error` message for medias and `Puppeteer dependencies not installed, run npm install @nesk/pupheteer` --no-save (which is done in the Dockerfile???)

Any feedback on my Dockerfile is welcome, and obviously any part of it can be reused for the repo.
